---
services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: novashop-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: novashop
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./infrastructure/docker/mongodb/init-scripts:/docker-entrypoint-initdb.d
      - ./infrastructure/docker/mongodb/mongod.conf:/etc/mongod.conf
    networks:
      - novashop-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Mongo Express - Web-based MongoDB admin interface
  mongo-express:
    image: mongo-express:1.0.0
    container_name: novashop-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: false
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - novashop-network

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: novashop-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - novashop-network

  # Kafka Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: novashop-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - novashop-network

  # Order Service
  order-service:
    build: ./services/order-service
    container_name: novashop-order-service
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/orderdb?authSource=admin
      - KAFKA_BROKER=kafka:9092
      - PORT=3001
    volumes:
      - ./services/order-service:/app
      - /app/node_modules
    networks:
      - novashop-network

  # Product Service (disabled by default - incomplete)
  product-service:
    build: ./services/product-service
    container_name: novashop-product-service
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/productdb?authSource=admin
      - KAFKA_BROKER=kafka:9092
      - PORT=3002
    volumes:
      - ./services/product-service:/app
      - /app/node_modules
    networks:
      - novashop-network
    profiles:
      - disabled

  # Payment Service (disabled by default - incomplete)
  payment-service:
    build: ./services/payment-service
    container_name: novashop-payment-service
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/paymentdb?authSource=admin
      - KAFKA_BROKER=kafka:9092
      - PORT=3003
    volumes:
      - ./services/payment-service:/app
      - /app/node_modules
    networks:
      - novashop-network
    profiles:
      - disabled

volumes:
  mongodb_data:
    driver: local

networks:
  novashop-network:
    driver: bridge
