apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: novashop
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-external
  namespace: novashop
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30017
    protocol: TCP
  selector:
    app: mongodb
