apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: novashop
data:
  mongod.conf: |
    # MongoDB Configuration File
    net:
      port: 27017
      bindIpAll: true
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    processManagement:
      fork: false
    security:
      authorization: enabled
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
      verbosity: 1
